# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xFn7E_Nzq_e1MsErQjDBDJJuNceZQKpz
"""
import pandas as pd
import sys
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import style
from datetime import datetime
from pandas.plotting import register_matplotlib_converters
from IPython import display
import time


plt.ion()
style.use('ggplot')
register_matplotlib_converters()

VOLUME_CHART_HEIGHT = 0.33

class BitcoinTradingGraph:
    """A Bitcoin trading visualization using matplotlib made to render OpenAI gym environments"""

    def __init__(self, df):
        df=df.reset_index(level=0)# ok
        df["Date"]=pd.to_datetime(df['Date']).apply(lambda x: x.date())
        self.df = df

        
        #print("wtffffffff")
        #print(self.df)
        self.df['Time'] = self.df['Date'] #.apply(
            #lambda x: datetime.strptime(str(x), '%Y-%m-%d %H:%M:%S')) # %I-%p
        
        # d = datetime.fromisoformat('2020-01-06T00:00:00.000Z'[:-1]).astimezone(timezone.utc)
        #print(self.df['Time'])
        #self.df['Time'] = self.df['Date'].dt.strftime('%Y-%m-%d')
        
        self.df = self.df.sort_values('Time')

        # Create a figure on screen and set the title
        #self.fig = plt.figure()

        # Create top subplot for net worth axis
        # self.net_worth_ax = plt.subplot2grid(
        #     (6, 1), (0, 0), rowspan=2, colspan=1)

        # Create bottom subplot for shared price/volume axis
        # self.price_ax = plt.subplot2grid(
        #     (6, 1), (2, 0), rowspan=8, colspan=1, sharex=self.net_worth_ax)

        # Create a new axis for volume which shares its x-axis with price
        
        # self.volume_ax = self.price_ax.twinx()

        # Add padding to make graph easier to view
        # plt.subplots_adjust(left=0.11, bottom=0.24,
        #                     right=0.90, top=0.90, wspace=0.2, hspace=0)

        
        # Show the graph without blocking the rest of the program
        
        #plt.show(block=False)

    def _render_net_worth(self, step_range, dates, current_step, net_worths, benchmarks,trades,net_worth,initial_net_worth,profit_percent):
       
        plt.clf()

        fig = plt.figure()
        fig.suptitle('Net worth: $' + str(net_worth) + ' | Profit: ' + str(profit_percent) + '%')
           
        
        #plt.plot(dates, net_worths[step_range], label='Net Worth', color="g")

        # Plot 1st subplot - net worths
        

        net_worth_ax = plt.subplot2grid((6, 1), (0, 0), rowspan=2, colspan=1)
        net_worth_ax.cla()
        net_worth_ax.plot(dates, net_worths[step_range], label='Net Worth', color="g")

        # benchmarks 

        colors = ['orange', 'cyan', 'purple', 'blue', 'magenta', 'yellow', 'black', 'red', 'green']

        for i, benchmark in enumerate(benchmarks):
            net_worth_ax.plot(dates, benchmark['values'][step_range], label=benchmark['label'], color=colors[i % len(colors)], alpha=0.3)
  

        # Show legend, which uses the label we defined for the plot above
        net_worth_ax.legend()
        legend = net_worth_ax.legend(loc=2, ncol=2, prop={'size': 8})
        legend.get_frame().set_alpha(0.4)

        last_date = self.df['Time'].values[current_step]
        last_net_worth = net_worths[current_step]
        
        # Annotate the current net worth on the net worth graph
        net_worth_ax.annotate('{0:.2f}'.format(last_net_worth), (last_date, last_net_worth),
                                   xytext=(last_date, last_net_worth),
                                   bbox=dict(boxstyle='round',
                                             fc='w', ec='k', lw=1),
                                   color="black",
                                   fontsize="small")

        # Add space above and below min/max net worth
        net_worth_ax.set_ylim(min(net_worths) / 1.25, max(net_worths) * 1.25)




        
        # Plot 2nd subplot - net worths
        # Create bottom subplot for shared price/volume axis
        
        price_ax = plt.subplot2grid((6, 1), (2, 0), rowspan=8, colspan=1) #sharex=net_worth_ax)
        price_ax .cla()
        price_ax.plot(dates, self.df['Close'].values[step_range], color="black")

        last_date = self.df['Time'].values[current_step]
        last_close = self.df['Close'].values[current_step]
        last_high = self.df['High'].values[current_step]

        # Print the current price to the price axis
        price_ax.annotate('{0:.2f}'.format(last_close), (last_date, last_close),
                               xytext=(last_date, last_high),
                               bbox=dict(boxstyle='round',
                                         fc='w', ec='k', lw=1),
                               color="black",
                               fontsize="small")
        ylim = price_ax.get_ylim()
        price_ax.set_ylim(ylim[0] - (ylim[1] - ylim[0])* VOLUME_CHART_HEIGHT, ylim[1])

        # Plot 2nd subplot - net worths
        volume = np.array(self.df['Volume'].values[step_range])
        volume_ax = price_ax.twinx()
        volume_ax.cla()
                
        volume_ax.plot(dates, volume,  color='blue')
        volume_ax.fill_between(dates, volume, color='blue', alpha=0.5)
        volume_ax.set_ylim(0, max(volume) / VOLUME_CHART_HEIGHT)
        volume_ax.yaxis.set_ticks([])

        for trade in trades:
                    if trade['step'] in range(sys.maxsize)[step_range]:
                        date = self.df['Time'].values[trade['step']]
                        close = self.df['Close'].values[trade['step']]

                        if trade['type'] == 'buy':
                            color = 'g'
                        else:
                            color = 'r'

                        price_ax.annotate(' ', (date, close),
                                              xytext=(date, close),
                                              size="large",
                                              arrowprops=dict(arrowstyle='simple', facecolor=color))
        
        date_labels = self.df['Date'].values[step_range]

        price_ax.set_xticklabels(date_labels, rotation=45, horizontalalignment='right')
       # Hide duplicate net worth date labels
        plt.setp(net_worth_ax.get_xticklabels(), visible=False)

        plt.subplots_adjust(left=0.11, bottom=0.24, right=0.90, top=0.90, wspace=0.2, hspace=0)

        # plt.show(block=False)
        display.clear_output(wait=True)
        display.display(plt.gcf())

        display.clear_output(wait=True)
        
        # Add padding to make graph easier to view
        # 

        time.sleep(2)
        plt.pause(0.1)

    def render(self, current_step, net_worths, benchmarks, trades, window_size=200):
        
        
        net_worth = round(net_worths[-1], 2)
        initial_net_worth = round(net_worths[0], 2)
        profit_percent = round((net_worth - initial_net_worth) / initial_net_worth * 100, 2)
        

        window_start = max(current_step - window_size, 0)
        step_range = slice(window_start, current_step + 1)
        dates = self.df['Time'].values[step_range]

        self._render_net_worth(step_range, dates, current_step, net_worths, benchmarks,trades,net_worth,initial_net_worth,profit_percent)
       
        # Necessary to view frames before they are unrendered
        #
    def close(self):
        plt.close()





